# -*- coding: utf-8 -*-
"""Manipulação de arquivos em python

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1qe5Ab7BN3pL4Cc9neqaVlNnRiKPecscL
"""



"""# Task
Gerar exemplos de código em Python para manipulação de arquivos, incluindo criação, leitura, escrita, adição de conteúdo, manipulação de arquivos CSV e JSON, verificação de existência, remoção, listagem, criação e remoção de diretórios, renomeação e obtenção de informações sobre arquivos.

## Criar um arquivo de texto

### Subtask:
Gerar código para criar e escrever em um arquivo de texto.

**Reasoning**:
Create and write to a text file as requested in the instructions.
"""

file_name = "example.txt"
with open(file_name, "w") as f:
    f.write("This is the first line.\n")
    f.write("This is the second line.\n")
    f.write("This is the third line.\n")

"""## Ler um arquivo de texto

### Subtask:
Gerar código para ler o conteúdo de um arquivo de texto.

**Reasoning**:
Read the content of the previously created "example.txt" file and print it.
"""

file_name = "example.txt"
with open(file_name, "r") as f:
    content = f.read()
print(content)

"""## Adicionar conteúdo a um arquivo

### Subtask:
Gerar código para adicionar conteúdo a um arquivo existente sem sobrescrever o conteúdo original.

**Reasoning**:
Create a code block to open the file "example.txt" in append mode and add a new line of text.
"""

file_name = "example.txt"
with open(file_name, "a") as f:
    f.write("This is a new appended line.\n")

"""## Manipular arquivos csv

### Subtask:
Gerar código para ler e escrever em arquivos CSV usando a biblioteca `csv`.

**Reasoning**:
Generate code to write and read CSV files using the `csv` library as per the instructions.
"""

import csv

# Data to be written to the CSV file
data = [
    ['Name', 'Age', 'City'],
    ['Alice', 30, 'New York'],
    ['Bob', 25, 'London'],
    ['Charlie', 35, 'Paris']
]

csv_file_name = "example.csv"

# Write data to the CSV file
with open(csv_file_name, mode='w', newline='') as file:
    writer = csv.writer(file)
    writer.writerows(data)

print(f"Data written to {csv_file_name}")

# Read data from the CSV file
print(f"\nReading data from {csv_file_name}:")
with open(csv_file_name, mode='r') as file:
    reader = csv.reader(file)
    for row in reader:
        print(row)

"""## Manipular arquivos json

### Subtask:
Gerar código para ler e escrever em arquivos JSON usando a biblioteca `json`.

**Reasoning**:
Import the `json` library, define data to be written to a JSON file, specify the file name, write the data to the file with indentation, print a confirmation message, read the data back from the file, and print the read data.
"""

import json

# Data to be written to the JSON file
data = {
    "name": "John Doe",
    "age": 30,
    "isStudent": False,
    "courses": [
        {"title": "Math", "credits": 3},
        {"title": "Science", "credits": 4}
    ]
}

json_file_name = "example.json"

# Write data to the JSON file
with open(json_file_name, 'w') as f:
    json.dump(data, f, indent=4)

print(f"Data written to {json_file_name}")

# Read data from the JSON file
print(f"\nReading data from {json_file_name}:")
with open(json_file_name, 'r') as f:
    read_data = json.load(f)

print(read_data)

"""## Verificar a existência de um arquivo

### Subtask:
Gerar código para verificar se um arquivo existe.

**Reasoning**:
Import the os module and define the file name, then use os.path.exists() to check for the file's existence and print the result.
"""

import os

file_name = "example.txt"

if os.path.exists(file_name):
  print(f"The file '{file_name}' exists.")
else:
  print(f"The file '{file_name}' does not exist.")

"""## Remover um arquivo

### Subtask:
Gerar código para remover um arquivo.

**Reasoning**:
Import the os module, define the file name, check if the file exists, and remove it if it does, printing a message to indicate the outcome.
"""

import os

file_name = "example.txt"

if os.path.exists(file_name):
    os.remove(file_name)
    print(f"The file '{file_name}' was removed.")
else:
    print(f"The file '{file_name}' does not exist.")

"""## Listar arquivos em um diretório

### Subtask:
Gerar código para listar arquivos em um diretório usando a biblioteca `os`.

**Reasoning**:
Import the os module, define the directory path, list the files in the directory, and print the list.
"""

import os

directory_path = "."  # Current directory

file_list = os.listdir(directory_path)

print(f"Files and directories in {directory_path}:")
for item in file_list:
    print(item)

"""## Criar um diretório

### Subtask:
Gerar código para criar um novo diretório.

**Reasoning**:
The subtask is to create a new directory. I will import the `os` module, define a directory name, check if it exists, and then create it using `os.makedirs()`.
"""

import os

new_directory_name = "my_new_directory"

if os.path.exists(new_directory_name):
    print(f"The directory '{new_directory_name}' already exists.")
else:
    os.makedirs(new_directory_name)
    print(f"The directory '{new_directory_name}' was created.")

"""## Remover um diretório

### Subtask:
Gerar código para remover um diretório.

**Reasoning**:
Import the `os` module, define the directory name, check if it exists, and remove it if it does, printing a confirmation message.
"""

import os

directory_to_remove = "my_new_directory"

if os.path.exists(directory_to_remove):
    os.rmdir(directory_to_remove)
    print(f"The directory '{directory_to_remove}' was removed.")
else:
    print(f"The directory '{directory_to_remove}' does not exist.")

"""## Renomear um arquivo ou diretório

### Subtask:
Gerar código para renomear um arquivo ou diretório.

**Reasoning**:
Generate code to rename a file or directory as per the instructions.
"""

import os

# Define the current and new names for the file or directory
old_name = "example.csv"  # Replace with the actual name
new_name = "renamed_example.csv" # Replace with the desired new name

# Check if the old name exists
if os.path.exists(old_name):
    # Rename the file or directory
    os.rename(old_name, new_name)
    print(f"Successfully renamed '{old_name}' to '{new_name}'.")
else:
    print(f"Error: The file or directory '{old_name}' was not found.")

"""## Obter informações sobre um arquivo

### Subtask:
Gerar código para obter informações como tamanho, data de modificação, etc., de um arquivo.

**Reasoning**:
The subtask requires getting file information, which involves importing the `os` and `datetime` modules, checking for file existence, using `os.stat()` to get file information, and then printing the size and modification time. These steps can be combined into a single code block.
"""

import os
import datetime

file_name = "renamed_example.csv"

if os.path.exists(file_name):
    file_info = os.stat(file_name)

    print(f"File Size: {file_info.st_size} bytes")

    # Convert modification time to a human-readable format
    mod_time_timestamp = file_info.st_mtime
    mod_time_datetime = datetime.datetime.fromtimestamp(mod_time_timestamp)
    print(f"Last Modification Time: {mod_time_datetime}")
else:
    print(f"The file '{file_name}' was not found.")

"""## Summary:

### Data Analysis Key Findings

*   Python's built-in `open()` function is used for basic file operations (create, read, write, append) using modes like `'w'`, `'r'`, and `'a'`.
*   The `with open(...)` construct is the recommended way to handle files as it ensures proper closing, even if errors occur.
*   The `csv` module is essential for structured reading and writing of CSV files, with `csv.writer` and `csv.reader` being key classes.
*   The `json` module is used for serializing and deserializing Python objects to and from JSON format, using `json.dump` for writing and `json.load` for reading.
*   The `os` module provides comprehensive functionalities for interacting with the operating system, including file and directory operations.
*   `os.path.exists()` is used to check if a file or directory exists.
*   `os.remove()` is used to delete files.
*   `os.rmdir()` is used to remove empty directories, while `os.makedirs()` creates directories (including intermediate ones).
*   `os.listdir()` is used to list the contents of a directory.
*   `os.rename()` is used to change the name of a file or directory.
*   `os.stat()` provides detailed information about a file, such as size (`st_size`) and modification time (`st_mtime`).
*   The `datetime` module is useful for converting timestamps obtained from `os.stat()` into human-readable date and time formats.

### Insights or Next Steps

*   Consider exploring more advanced file manipulation tasks, such as handling binary files or working with file permissions.
*   Investigate error handling for file operations (e.g., `FileNotFoundError`, `PermissionError`) to make the code more robust.

"""

# ============================================================
# 📁 MANIPULAÇÃO DE ARQUIVOS EM PYTHON — GUIA COMPLETO
# Autor: Guilherme Arthur de Carvalho - DIO | Adaptado por Josemar
# ============================================================

# 🔓 1. Abrindo e Fechando Arquivos
# ---------------------------------
# Usamos open() para abrir e close() para fechar arquivos.
# Modos: 'r' (leitura), 'w' (escrita), 'a' (anexar)

# Create the file first so it can be read later
try:
    with open("exemplo.txt", "w", encoding="utf-8") as f:
        f.write("Conteúdo inicial do arquivo exemplo.txt\n")
except Exception as e:
    print(f"Erro ao criar exemplo.txt: {e}")

# Exemplo 1: Abrir para leitura
f = open("exemplo.txt", "r", encoding="utf-8")

# Exemplo 2: Abrir para escrita (apaga conteúdo anterior)
f = open("exemplo.txt", "w", encoding="utf-8")

# Exemplo 3: Abrir para anexar conteúdo
f = open("exemplo.txt", "a", encoding="utf-8")

# Exemplo 4: Fechar o arquivo
f.close()


# 📖 2. Lendo de um Arquivo
# -------------------------
# Métodos: read(), readline(), readlines(), iteração linha a linha

with open("exemplo.txt", "r", encoding="utf-8") as f:
    # Exemplo 1: Ler todo o conteúdo
    conteudo = f.read()

with open("exemplo.txt", "r", encoding="utf-8") as f:
    # Exemplo 2: Ler uma linha
    linha = f.readline()

with open("exemplo.txt", "r", encoding="utf-8") as f:
    # Exemplo 3: Ler todas as linhas como lista
    linhas = f.readlines()

with open("exemplo.txt", "r", encoding="utf-8") as f:
    # Exemplo 4: Iterar linha a linha
    for linha in f:
        print(linha.strip())


# ✍️ 3. Escrevendo em um Arquivo
# ------------------------------
# Métodos: write(), writelines()

# Exemplo 1: Escrever texto simples
with open("saida.txt", "w", encoding="utf-8") as f:
    f.write("Olá, mundo!\n")

# Exemplo 2: Escrever múltiplas linhas
with open("saida.txt", "w", encoding="utf-8") as f:
    f.writelines(["Linha 1\n", "Linha 2\n"])

# Exemplo 3: Adicionar conteúdo sem apagar
with open("saida.txt", "a", encoding="utf-8") as f:
    f.write("Nova entrada\n")

# Exemplo 4: Criar novo arquivo e escrever
with open("novo.txt", "w", encoding="utf-8") as f:
    f.write("Arquivo criado com sucesso.")


# 🗂️ 4. Gerenciando Arquivos e Diretórios
# ---------------------------------------
# Módulos: os, shutil

import os
import shutil

# Exemplo 1: Criar diretório
# Check if directory exists before creating
if not os.path.exists("meu_diretorio"):
    os.mkdir("meu_diretorio")
    print("Diretório 'meu_diretorio' criado.")
else:
    print("Diretório 'meu_diretorio' já existe.")


# Exemplo 2: Renomear arquivo
# Create a dummy file to be renamed if it doesn't exist
dummy_file = "saida.txt"
if not os.path.exists(dummy_file):
    with open(dummy_file, "w", encoding="utf-8") as f:
        f.write("Conteúdo para renomear\n")
    print(f"Arquivo '{dummy_file}' criado para renomear.")

old_name = dummy_file
new_name = "saida_renomeada.txt"
if os.path.exists(old_name):
    os.rename(old_name, new_name)
    print(f"Arquivo '{old_name}' renomeado para '{new_name}'.")
else:
    print(f"Erro: Arquivo '{old_name}' não encontrado para renomear.")


# Exemplo 3: Excluir arquivo
# Create a dummy file to be removed if it doesn't exist
dummy_file_to_remove = "saida_renomeada.txt"
if not os.path.exists(dummy_file_to_remove):
     # Ensure the file exists if it was renamed in the previous step
     if os.path.exists("saida.txt"):
         os.rename("saida.txt", dummy_file_to_remove)
     else:
         with open(dummy_file_to_remove, "w", encoding="utf-8") as f:
             f.write("Conteúdo para remover\n")
         print(f"Arquivo '{dummy_file_to_remove}' criado para remoção.")

if os.path.exists(dummy_file_to_remove):
    os.remove(dummy_file_to_remove)
    print(f"Arquivo '{dummy_file_to_remove}' excluído.")
else:
    print(f"Erro: Arquivo '{dummy_file_to_remove}' não encontrado para excluir.")


# Exemplo 4: Copiar arquivo
# Create a dummy file to be copied if it doesn't exist
dummy_file_to_copy = "novo.txt"
if not os.path.exists(dummy_file_to_copy):
    with open(dummy_file_to_copy, "w", encoding="utf-8") as f:
        f.write("Conteúdo para copiar\n")
    print(f"Arquivo '{dummy_file_to_copy}' criado para cópia.")

source_file = dummy_file_to_copy
destination_file = "copia_novo.txt"
if os.path.exists(source_file):
    shutil.copy(source_file, destination_file)
    print(f"Arquivo '{source_file}' copiado para '{destination_file}'.")
else:
    print(f"Erro: Arquivo '{source_file}' não encontrado para copiar.")


# ⚠️ 5. Tratamento de Exceções
# ----------------------------
# Exceções comuns: FileNotFoundError, PermissionError, UnicodeDecodeError

# Exemplo 1: Arquivo não encontrado
try:
    open("inexistente.txt", "r")
except FileNotFoundError:
    print("Arquivo não existe.")

# Exemplo 2: Permissão negada (Este exemplo pode não funcionar em todos os ambientes)
# try:
#     open("/protegido.txt", "w")
# except PermissionError:
#     print("Sem permissão para escrever.")

# Exemplo 3: Erro de codificação
# Create a dummy file with a different encoding if it doesn't exist
dummy_encoding_file = "exemplo_iso.txt"
if not os.path.exists(dummy_encoding_file):
    with open(dummy_encoding_file, "w", encoding="iso-8859-1") as f:
        f.write("Conteúdo com caracteres especiais: çãé\n")
    print(f"Arquivo '{dummy_encoding_file}' criado com encoding ISO-8859-1.")

try:
    with open(dummy_encoding_file, encoding="ascii") as f:
        f.read()
except UnicodeDecodeError:
    print("Erro de decodificação.")

# Exemplo 4: Garantir fechamento com finally
# Create the file if it doesn't exist
if not os.path.exists("exemplo.txt"):
     with open("exemplo.txt", "w", encoding="utf-8") as f:
         f.write("Conteúdo para teste finally\n")
     print("Arquivo 'exemplo.txt' criado para teste finally.")

f = None # Initialize f to None
try:
    f = open("exemplo.txt", "r")
finally:
    if f: # Check if f is not None before closing
        f.close()
        print("Arquivo 'exemplo.txt' fechado no finally.")


# ✅ 6. Boas Práticas
# ------------------
# Usar 'with', verificar existência, definir codificação, tratar exceções

# Exemplo 1: Usar with para garantir fechamento
# Create the file if it doesn't exist
if not os.path.exists("exemplo.txt"):
     with open("exemplo.txt", "w", encoding="utf-8") as f:
         f.write("Conteúdo para teste with\n")
     print("Arquivo 'exemplo.txt' criado para teste with.")

with open("exemplo.txt", "r", encoding="utf-8") as f:
    print("Conteúdo lido com 'with':")
    print(f.read())

# Exemplo 2: Verificar existência antes de abrir
# Create the file if it doesn't exist
if not os.path.exists("exemplo.txt"):
     with open("exemplo.txt", "w", encoding="utf-8") as f:
         f.write("Conteúdo para teste exists\n")
     print("Arquivo 'exemplo.txt' criado para teste exists.")

if os.path.exists("exemplo.txt"):
    with open("exemplo.txt", "r", encoding="utf-8") as f: # Added encoding
        print("Conteúdo lido após verificar existência:")
        print(f.read())

# Exemplo 3: Definir codificação correta
# Create the file if it doesn't exist
if not os.path.exists("exemplo.txt"):
     with open("exemplo.txt", "w", encoding="utf-8") as f:
         f.write("Conteúdo para teste encoding\n")
     print("Arquivo 'exemplo.txt' criado para teste encoding.")

with open("exemplo.txt", encoding="utf-8") as f:
    print("Conteúdo lido com encoding especificado:")
    print(f.read())

# Exemplo 4: Tratar exceções ao abrir
# Create the file if it doesn't exist
if not os.path.exists("exemplo.txt"):
     with open("exemplo.txt", "w", encoding="utf-8") as f:
         f.write("Conteúdo para teste exceção ao abrir\n")
     print("Arquivo 'exemplo.txt' criado para teste exceção ao abrir.")

try:
    with open("exemplo.txt", "r", encoding="utf-8") as f: # Added encoding
        print("Conteúdo lido com tratamento de exceção:")
        print(f.read())
except Exception as e:
    print(f"Erro: {e}")


# 📊 7. Trabalhando com Arquivos CSV
# ----------------------------------
# Módulo: csv | Métodos: reader, writer

import csv

# Create a dummy CSV file if it doesn't exist
dummy_csv_file = "dados.csv"
if not os.path.exists(dummy_csv_file):
    with open(dummy_csv_file, "w", newline='', encoding="utf-8") as f:
        writer = csv.writer(f)
        writer.writerow(["Header1", "Header2"])
        writer.writerow(["Value1", "Value2"])
    print(f"Arquivo '{dummy_csv_file}' criado para teste CSV.")


# Exemplo 1: Ler CSV
try: # Added try-except block
    with open("dados.csv", newline='', encoding="utf-8") as f:
        leitor = csv.reader(f)
        print("\nConteúdo lido do CSV:")
        for linha in leitor:
            print(linha)
except FileNotFoundError:
    print("Arquivo 'dados.csv' não encontrado.")


# Exemplo 2: Escrever CSV
with open("saida.csv", "w", newline='', encoding="utf-8") as f:
    escritor = csv.writer(f)
    escritor.writerow(["Nome", "Idade"])
    escritor.writerow(["Ana", 30])
    print("\nArquivo 'saida.csv' criado e escrito.")


# Exemplo 3: Ler com tratamento de exceções
try:
    with open("dados.csv", newline='', encoding="utf-8") as f: # Added encoding
        leitor = csv.reader(f)
        print("\nConteúdo lido do CSV com tratamento de exceções:")
        for linha in leitor:
            print(linha)
except FileNotFoundError:
    print("Arquivo CSV não encontrado.")

# Exemplo 4: Escrever múltiplas linhas
dados = [["Produto", "Preço"], ["Caneta", 2.5], ["Caderno", 15.0]]
with open("produtos.csv", "w", newline='', encoding="utf-8") as f:
    escritor = csv.writer(f)
    escritor.writerows(dados)
    print("\nArquivo 'produtos.csv' criado e escrito com múltiplas linhas.")